const asset = name => `assets/${name}.svg`;
const ITEMS = {
  cat:['Кот','cat','animals'], butterfly:['Бабочка','butterfly','animals'], jellyfish:['Медуза','jellyfish','animals'], dog:['Собака','dog','animals'], coral:['Коралл','coral','animals'], hedgehog:['Ёж','hedgehog','animals'], whale:['Кит','whale','animals'], ant:['Муравей','ant','animals'], wolf:['Волк','wolf','animals'], fox:['Лиса','fox','animals'], bear:['Медведь','bear','animals'],
  oak:['Дуб','tree','plants'], daisy:['Ромашка','flower','plants'], spruce:['Ель','evergreen','plants'], birch:['Берёза','tree','plants'], cactus:['Кактус','cactus','plants'], algae:['Водоросль','leaf','plants'],
  mushroom:['Мухомор','mushroom','fungi'], champignon:['Шампиньон','mushroom','fungi'], mold:['Плесень','mold','fungi'], yeast:['Дрожжи','yeast','fungi'], tinder:['Трутовик','mushroom','fungi'],
  yogurt:['Бактерия йогурта','microbe','bacteria'], ecoli:['Кишечная палочка','microbe2','bacteria'], microscopeB:['Бактерия в микроскопе','microscope','bacteria'], soilB:['Почвенная бактерия','microbe3','bacteria'], toothB:['Бактерия на зубах','microbe4','bacteria']
};
const KINGDOMS={animals:'Зал животных',plants:'Оранжерея растений',fungi:'Пещера грибов',bacteria:'Лаборатория бактерий'};
const state={screen:0,stars:0,earned:new Set(),selected:null,oddRound:0};
const screens=[...document.querySelectorAll('.screen')];
const toast=document.getElementById('toast');
function showToast(text){toast.textContent=text;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1800)}
function goTo(n){state.screen=Math.max(0,Math.min(screens.length-1,n));screens.forEach((s,i)=>s.classList.toggle('active',i===state.screen));document.getElementById('progressFill').style.width=`${(state.screen+1)*10}%`;document.getElementById('progressText').textContent=`Зал ${state.screen+1} из 10`;scrollTo({top:0,behavior:'smooth'});if(state.screen===7)renderOdd();}
function earn(key){if(!state.earned.has(key)){state.earned.add(key);state.stars++;document.getElementById('starCount').textContent=state.stars;showToast('★ Новая звезда!')}}
document.querySelectorAll('[data-next]').forEach(b=>b.addEventListener('click',()=>goTo(state.screen+1)));
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>goTo(+b.dataset.go)));
document.querySelectorAll('[data-fact]').forEach(b=>b.addEventListener('click',()=>{document.getElementById('kingdomFact').textContent=b.dataset.fact;b.parentElement.querySelectorAll('button').forEach(x=>x.removeAttribute('aria-pressed'));b.setAttribute('aria-pressed','true')}));

function card(key,kind='specimen-card'){const [label,img,kingdom]=ITEMS[key];const el=document.createElement('button');el.type='button';el.className=kind;el.dataset.key=key;el.dataset.kingdom=kingdom;el.draggable=kind==='specimen-card';el.innerHTML=`<img src="${asset(img)}" alt=""><span>${label}</span>`;return el}
function buildSort(id,keys){const board=document.querySelector(`[data-sort-board="${id}"]`),tray=document.querySelector(`[data-card-tray="${id}"]`);Object.entries(KINGDOMS).forEach(([k,label])=>{const z=document.createElement('div');z.className=`drop-zone ${k}`;z.dataset.kingdom=k;z.innerHTML=`<h3>${label}</h3>`;board.append(z)});keys.forEach(k=>tray.append(card(k)));wireSort(id)}
function wireSort(id){const board=document.querySelector(`[data-sort-board="${id}"]`),tray=document.querySelector(`[data-card-tray="${id}"]`),hint=document.querySelector(`[data-hint="${id}"]`);let dragged=null;tray.addEventListener('dragstart',e=>{const c=e.target.closest('.specimen-card');if(c){dragged=c;setTimeout(()=>c.style.opacity=.45)}});tray.addEventListener('dragend',()=>{if(dragged)dragged.style.opacity='';dragged=null});[...board.querySelectorAll('.drop-zone')].forEach(z=>{z.addEventListener('dragover',e=>{e.preventDefault();z.classList.add('drag-over')});z.addEventListener('dragleave',()=>z.classList.remove('drag-over'));z.addEventListener('drop',e=>{e.preventDefault();z.classList.remove('drag-over');if(dragged)place(dragged,z,id,hint,tray)});z.addEventListener('click',()=>{if(state.selected)place(state.selected,z,id,hint,tray)})});tray.addEventListener('click',e=>{const c=e.target.closest('.specimen-card');if(!c)return;tray.querySelectorAll('.selected').forEach(x=>x.classList.remove('selected'));state.selected=c;c.classList.add('selected');board.querySelectorAll('.drop-zone').forEach(x=>x.classList.add('selected-target'));hint.textContent=`Выбран экспонат «${ITEMS[c.dataset.key][0]}». Теперь выбери зал.`})}
function place(c,z,id,hint,tray){boardClear(z.closest('.drop-grid'));if(c.dataset.kingdom===z.dataset.kingdom){c.classList.remove('selected');c.draggable=false;z.append(c);state.selected=null;hint.textContent='Верно! Отличная работа.';hint.className='game-hint good';if(!tray.querySelector('.specimen-card')){document.querySelector(`[data-success="${id}"]`).classList.add('show');earn(id)}}else{c.classList.add('shake');setTimeout(()=>c.classList.remove('shake'),400);hint.textContent=hintFor(c.dataset.kingdom);hint.className='game-hint try'} }
function boardClear(board){board.querySelectorAll('.drop-zone').forEach(x=>x.classList.remove('selected-target'))}
function hintFor(k){return {animals:'Почти! Может ли это существо двигаться или есть готовую пищу?',plants:'Подумай, умеет ли оно делать пищу с помощью света.',fungi:'Вспомни: плесень и дрожжи — тоже грибы.',bacteria:'Возможно, без микроскопа его не разглядеть.'}[k]}
buildSort('first',['cat','butterfly','jellyfish','oak','daisy','spruce','mushroom','mold','yeast','yogurt','ecoli','microscopeB']);
buildSort('final',['dog','butterfly','jellyfish','coral','hedgehog','oak','daisy','cactus','algae','spruce','mushroom','champignon','mold','yeast','tinder','yogurt','ecoli','microscopeB','soilB','toothB']);

const choiceGames={
 animals:{keys:['dog','jellyfish','coral','butterfly','mushroom','birch'],correct:['dog','jellyfish','coral','butterfly'],success:'Верно! Даже коралл — животное, хотя похож на растение.'},
 visible:{keys:['whale','ant','cat','yogurt','ecoli'],correct:['whale','ant','cat'],success:'Точно! Бактерии можно рассмотреть только с увеличением.'}
};
Object.entries(choiceGames).forEach(([id,g])=>{const box=document.querySelector(`[data-choice-game="${id}"]`);g.keys.forEach(k=>box.append(card(k,'choice-card')));box.addEventListener('click',e=>{const c=e.target.closest('.choice-card');if(c)c.classList.toggle('selected')})});
const plantBox=document.querySelector('[data-choice-game="plant"]');const plantItems=[['Солнечный свет','sun',1],['Вода','water',1],['Углекислый газ','air',1],['Колбаса','sausage',0],['Шоколад','chocolate',0],['Гамбургер','burger',0],['Молоко','milk',0]];plantItems.forEach(([label,img,ok],i)=>{const el=document.createElement('button');el.className='choice-card';el.dataset.key=`p${i}`;el.dataset.ok=ok;el.innerHTML=`<img src="${asset(img)}" alt=""><span>${label}</span>`;plantBox.append(el)});plantBox.addEventListener('click',e=>{const c=e.target.closest('.choice-card');if(c)c.classList.toggle('selected')});
document.querySelectorAll('[data-check-choice]').forEach(b=>b.addEventListener('click',()=>checkChoice(b.dataset.checkChoice)));
function checkChoice(id){const box=document.querySelector(`[data-choice-game="${id}"]`),selected=[...box.querySelectorAll('.selected')],hint=document.querySelector(`[data-choice-hint="${id}"]`);let ok=false;if(id==='plant'){ok=selected.length===3&&selected.every(x=>x.dataset.ok==='1')}else{const want=choiceGames[id].correct;ok=selected.length===want.length&&selected.every(x=>want.includes(x.dataset.key))}if(ok){selected.forEach(x=>x.classList.add('correct'));hint.textContent=id==='plant'?'Растение приготовило себе еду!':choiceGames[id].success;hint.className='game-hint good';document.querySelector(`[data-choice-next="${id}"]`).classList.remove('hidden');bDisable(id);earn(id);if(id==='plant'){document.querySelector('.plant-stage').classList.add('alive');document.querySelector('[data-plant-slots]').innerHTML='<span>☀</span><span>💧</span><span>CO₂</span>'}}else{selected.forEach(x=>{if(id==='plant'?x.dataset.ok!=='1':!choiceGames[id].correct.includes(x.dataset.key))x.classList.add('wrong')});hint.textContent='Почти! Проверь выбранные карточки и попробуй ещё раз.';hint.className='game-hint try';setTimeout(()=>box.querySelectorAll('.wrong').forEach(x=>x.classList.remove('wrong')),500)}}
function bDisable(id){document.querySelector(`[data-check-choice="${id}"]`).classList.add('hidden')}
document.querySelectorAll('[data-quiz] button').forEach(b=>b.addEventListener('click',()=>{const hint=document.querySelector('[data-quiz-hint="fungi"]');if(b.dataset.answer==='fungi'){b.classList.add('correct');hint.textContent='Верно! Плесень — это тоже гриб. Грибы бывают не только в лесу.';hint.className='game-hint good';document.querySelector('[data-quiz-next="fungi"]').classList.remove('hidden');earn('fungi')}else{b.classList.add('wrong');hint.textContent='Почти! Вспомни, к какому царству относится плесень.';setTimeout(()=>b.classList.remove('wrong'),500)}}));

const rounds=[
 {keys:['wolf','fox','bear','birch'],odd:'birch'}, {keys:['mushroom','mold','yeast','daisy'],odd:'daisy'},
 {keys:['oak','spruce','cactus','yogurt'],odd:'yogurt'}, {keys:['yogurt','ecoli','microscopeB','butterfly'],odd:'butterfly'}
];
function renderOdd(){const r=rounds[state.oddRound],grid=document.getElementById('oddGrid');grid.innerHTML='';document.getElementById('roundLabel').textContent=`Раунд ${state.oddRound+1} из 4`;document.getElementById('oddHint').textContent='Найди того, кто относится к другому царству.';document.getElementById('oddNext').classList.add('hidden');r.keys.forEach(k=>{const c=card(k,'odd-card');c.addEventListener('click',()=>chooseOdd(c,k));grid.append(c)})}
function chooseOdd(c,k){const r=rounds[state.oddRound],hint=document.getElementById('oddHint');if(k===r.odd){c.classList.add('correct');hint.textContent=`Верно! ${ITEMS[k][0]} относится к другому царству.`;hint.className='game-hint good';document.getElementById('oddNext').classList.remove('hidden');document.querySelectorAll('.odd-card').forEach(x=>x.disabled=true)}else{c.classList.add('wrong');hint.textContent='Не совсем. Посмотри, какие трое относятся к одному царству.';setTimeout(()=>c.classList.remove('wrong'),500)}}
document.getElementById('oddNext').addEventListener('click',()=>{if(state.oddRound<3){state.oddRound++;renderOdd()}else{earn('odd');goTo(8)}});
document.getElementById('restart').addEventListener('click',()=>location.reload());
goTo(0);
